/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import * as z from "zod";

export type CreateUserRawResponse =
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Buffer
    | Uint8Array
    | string;

/** @internal */
export const CreateUserRawResponse$inboundSchema: z.ZodType<
    CreateUserRawResponse,
    z.ZodTypeDef,
    unknown
> = z.union([
    z.union([
        z.instanceof(ReadableStream<Uint8Array>),
        z.instanceof(Blob),
        z.instanceof(ArrayBuffer),
        z.instanceof(Buffer),
    ]),
    b64$.zodInbound,
]);

/** @internal */
export type CreateUserRawResponse$Outbound =
    | ReadableStream<Uint8Array>
    | Blob
    | ArrayBuffer
    | Buffer
    | Uint8Array;

/** @internal */
export const CreateUserRawResponse$outboundSchema: z.ZodType<
    CreateUserRawResponse$Outbound,
    z.ZodTypeDef,
    CreateUserRawResponse
> = z.union([
    z.union([
        z.instanceof(ReadableStream<Uint8Array>),
        z.instanceof(Blob),
        z.instanceof(ArrayBuffer),
        z.instanceof(Buffer),
    ]),
    b64$.zodOutbound,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUserRawResponse$ {
    /** @deprecated use `CreateUserRawResponse$inboundSchema` instead. */
    export const inboundSchema = CreateUserRawResponse$inboundSchema;
    /** @deprecated use `CreateUserRawResponse$outboundSchema` instead. */
    export const outboundSchema = CreateUserRawResponse$outboundSchema;
    /** @deprecated use `CreateUserRawResponse$Outbound` instead. */
    export type Outbound = CreateUserRawResponse$Outbound;
}
