/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as b64$ from "../../lib/base64.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type GetOrderByIdRequest = {
    /**
     * ID of order that needs to be fetched
     */
    orderId: number;
};

export type GetOrderByIdResponse = components.Order1 | Uint8Array | string;

/** @internal */
export const GetOrderByIdRequest$inboundSchema: z.ZodType<
    GetOrderByIdRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    orderId: z.number().int(),
});

/** @internal */
export type GetOrderByIdRequest$Outbound = {
    orderId: number;
};

/** @internal */
export const GetOrderByIdRequest$outboundSchema: z.ZodType<
    GetOrderByIdRequest$Outbound,
    z.ZodTypeDef,
    GetOrderByIdRequest
> = z.object({
    orderId: z.number().int(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdRequest$ {
    /** @deprecated use `GetOrderByIdRequest$inboundSchema` instead. */
    export const inboundSchema = GetOrderByIdRequest$inboundSchema;
    /** @deprecated use `GetOrderByIdRequest$outboundSchema` instead. */
    export const outboundSchema = GetOrderByIdRequest$outboundSchema;
    /** @deprecated use `GetOrderByIdRequest$Outbound` instead. */
    export type Outbound = GetOrderByIdRequest$Outbound;
}

/** @internal */
export const GetOrderByIdResponse$inboundSchema: z.ZodType<
    GetOrderByIdResponse,
    z.ZodTypeDef,
    unknown
> = z.union([components.Order1$inboundSchema, b64$.zodInbound]);

/** @internal */
export type GetOrderByIdResponse$Outbound = components.Order1$Outbound | Uint8Array;

/** @internal */
export const GetOrderByIdResponse$outboundSchema: z.ZodType<
    GetOrderByIdResponse$Outbound,
    z.ZodTypeDef,
    GetOrderByIdResponse
> = z.union([components.Order1$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetOrderByIdResponse$ {
    /** @deprecated use `GetOrderByIdResponse$inboundSchema` instead. */
    export const inboundSchema = GetOrderByIdResponse$inboundSchema;
    /** @deprecated use `GetOrderByIdResponse$outboundSchema` instead. */
    export const outboundSchema = GetOrderByIdResponse$outboundSchema;
    /** @deprecated use `GetOrderByIdResponse$Outbound` instead. */
    export type Outbound = GetOrderByIdResponse$Outbound;
}
