/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as z from "zod";

export type UpdateUserJsonRequest = {
    /**
     * name that needs to be updated
     */
    username: string;
    /**
     * Update an existent user in the store
     */
    user?: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Buffer | undefined;
};

/** @internal */
export const UpdateUserJsonRequest$inboundSchema: z.ZodType<
    UpdateUserJsonRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        username: z.string(),
        User: z
            .union([
                z.instanceof(ReadableStream<Uint8Array>),
                z.instanceof(Blob),
                z.instanceof(ArrayBuffer),
                z.instanceof(Buffer),
            ])
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            User: "user",
        });
    });

/** @internal */
export type UpdateUserJsonRequest$Outbound = {
    username: string;
    User?: ReadableStream<Uint8Array> | Blob | ArrayBuffer | Buffer | undefined;
};

/** @internal */
export const UpdateUserJsonRequest$outboundSchema: z.ZodType<
    UpdateUserJsonRequest$Outbound,
    z.ZodTypeDef,
    UpdateUserJsonRequest
> = z
    .object({
        username: z.string(),
        user: z
            .union([
                z.instanceof(ReadableStream<Uint8Array>),
                z.instanceof(Blob),
                z.instanceof(ArrayBuffer),
                z.instanceof(Buffer),
            ])
            .optional(),
    })
    .transform((v) => {
        return remap$(v, {
            user: "User",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateUserJsonRequest$ {
    /** @deprecated use `UpdateUserJsonRequest$inboundSchema` instead. */
    export const inboundSchema = UpdateUserJsonRequest$inboundSchema;
    /** @deprecated use `UpdateUserJsonRequest$outboundSchema` instead. */
    export const outboundSchema = UpdateUserJsonRequest$outboundSchema;
    /** @deprecated use `UpdateUserJsonRequest$Outbound` instead. */
    export type Outbound = UpdateUserJsonRequest$Outbound;
}
